import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { FlagOrpheusTop } from "@/components/icons/FlagOrpheusTop";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white transition-colors duration-300`}
      >
        <div className="fixed top-0 right-8 z-50 w-32 md:w-48 transition-transform hover:rotate-3 origin-top-right">
          <a href="https://hackclub.com" target="_blank" rel="noopener noreferrer">
            <FlagOrpheusTop className="w-full drop-shadow-md" />
          </a>
        </div>
        {children}
      </body>
    </html>
  );
}
